{% set name = "inequality" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acdfb22513cf278ee273942d71e0a6a1ba40e1da4a9e0a657cb1a032df3eb646

build:
  skip: true  # [py<312]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
    - setuptools-scm >=6.2
  run:
    - python
    - libpysal >=4.12
    - matplotlib-base >=3.10
    - numpy >=2.0
    - pandas >=2.3
    - scipy >=1.14
    - joblib
    - tqdm

test:
  source_files:
    - inequality/tests
  imports:
    - inequality
  requires:
    - pip
    - pytest
    - seaborn
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv inequality/tests

about:
  home: https://github.com/pysal/inequality
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Spatial inequality analysis for PySAL.
  description: |
    inequality implements measures for the analysis of inequality over space and time and is
    part of the PySAL family.
  doc_url: https://pysal.org/inequality
  dev_url: https://github.com/pysal/inequality

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
