{% set name = "inequality" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2010253c26cfe3745d36beb02aeff5503e1b21cb06e1d52aa7f13c37acd9adf1

build:
  skip: true  # [py<311]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
    - wheel
  run:
    - python
    - libpysal >=4.12
    - matplotlib >=3.8
    - numpy >=1.26
    - pandas >=2.1
    - scipy >=1.12

test:
  source_files:
    - inequality/tests
  imports:
    - inequality
  requires:
    - pip
    - pytest
    - seaborn
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv inequality/tests

about:
  home: https://github.com/pysal/inequality
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Spatial inequality analysis for PySAL.
  description: |
    inequality implements measures for the analysis of inequality over space and time and is
    part of the PySAL family.
  doc_url: https://pysal.org/inequality
  dev_url: https://github.com/pysal/inequality

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
